### ISSUE TITLE
Make basic CSV with correspondences

### ISSUE THREAD

**Issue by sunmuffin42** [grizgar/UMA-to-IPA#1]
Make the simple CSV with which characters in K'ichee' match to which characters in IPA

**Comment by grizgar** [comment]
[K'iche' Simple Correspondence Table.csv](https://github.com/grizgar/UMA-to-IPA/files/10762523/K.iche.Simple.Correspondence.Table.csv)

UMA	IPA
p	p
t	t
c	c
k	k
q	q
'	ʔ
b'	ɓ
t'	t'
c'	c'
k'	k'
q'	q'
tz	ts
ch	tʃ
tz'	ts'
ch'	tʃ'
j	χ
m	m
n	n
l	l
r	r
w	w
y	j
ä	a
a	a
a	aː
aa	aː
e	e
ë	e
e	eː
ee	eː
ï	i
i	iː
i	i
ii	iː
ö	o
o	oː
o	o
oo	oː
ü	u
u	uː
u	u
uu	uː
